python: 2.7

install:
  - pip install -U uiautomator
  - pip install -U imglib
  - pip install -U nose
  - pip install -U mtbfplugins

  --setup.py 

before_script:
  - echo "Before script..."
  - which monkeyrunner
  - which nosetests

script:
  - nosetests -w ./

after_script:
  - echo "after_script"
