python: 2.7

install:
  - pip install -U uiautomator

before_script:
  - echo "Before script..."
  - echo ANDROID_HOME
  - which monkeyrunner

script:
  - $ANDROID_HOME/tools/monkeyrunner test.py

after_script:
  - echo "after_script"
